export const siteMeta = {
  name: "夜航船之书",
  version: "0.0.3",
  githubHref: "https://github.com/xuelinf/nightsailing",
  headline: "把独自造出的 AI 工具，收入一册可被翻阅的船志。",
  edition: "庚午夏 · 观 Laper 后三校",
};

export const products = [
  {
    slug: "ai-sailing-log",
    name: "AI航行日记",
    shortName: "航行日记",
    index: "01",
    status: "available",
    statusLabel: "可下载",
    openSourceLabel: "已开源",
    platform: "macOS",
    stage: "已发布",
    visual: "ai-sailing-log",
    downloadHref: "/downloads/AI航行日记-0.1.0.dmg",
    sourceHref: "https://github.com/xuelinf/vibe-token-usage",
    summary: "把分散在本机的 AI 使用轨迹整理成一册菜单栏日记。",
    manifesto: "给频繁与模型同行的人，一个安静看见自己工作节奏的地方。",
    detail: "它不把数据包装成焦虑的仪表盘，而是把 Codex 与 Claude Code 的使用记录收拢成今日、周期和热力图。你可以知道自己在何时借力、何处消耗、何时该停船靠岸。",
    privacy: "默认只读取本机日志，不上传数据。",
    features: ["Codex 与 Claude Code 用量聚合", "今日 token 与额度窗口", "近期使用热力图", "macOS 菜单栏常驻"],
    scenes: ["检查当日额度", "复盘近期使用峰谷", "长期观察 AI 工作节奏"],
    evidence: ["今日 42k token", "额度窗口 5h", "热力图 14 日"],
    prompt: "查看今天和过去两周的 AI 使用节奏",
    nextStep: "补充真实菜单栏截图与小时分布演示",
    releaseNote: "首个可下载工具，也是整本“夜航船之书”的计量舱。",
    mediaSlots: ["真实截图位", "使用演示位", "更新日志位"],
  },
  {
    slug: "wenxuan",
    name: "问玄",
    shortName: "问玄",
    index: "02",
    status: "available",
    statusLabel: "可下载",
    openSourceLabel: "暂未开源",
    platform: "macOS",
    stage: "已发布",
    visual: "wenxuan",
    downloadHref: "/downloads/问玄.dmg",
    sourceHref: "",
    summary: "把起卦、排盘与 AI 参断收进一个克制的桌面流程。",
    manifesto: "让传统的结构感和当代模型的解释力，在一个小工具里相遇。",
    detail: "问玄不是把古老语汇做成噱头，而是把提问、摇卦、排盘和模型解读整理成可重复的流程。它保留仪式感，也把卦盘数据以结构化方式交给 AI 参断。",
    privacy: "AI 解卦通过本地代理读取模型密钥，前端不暴露 API key。",
    features: ["铜钱起卦交互", "六爻结构化排盘", "AI 解卦入口", "macOS 托盘应用"],
    scenes: ["记录问题", "生成卦盘", "调用模型生成参断"],
    evidence: ["三枚铜钱", "六爻排盘", "模型参断"],
    prompt: "把一次起卦整理成结构化问题和解释",
    nextStep: "补充起卦过程视频与卦盘真实截图",
    releaseNote: "第二个可下载工具，偏向东方文本、结构化数据和 AI 解释的交界。",
    mediaSlots: ["卦盘截图位", "起卦动效位", "解读示例位"],
  },
  {
    slug: "port-keeper",
    name: "端口占用管理器",
    shortName: "端口管理",
    index: "03",
    status: "planned",
    statusLabel: "计划中",
    openSourceLabel: "预留舱位",
    platform: "macOS / 本地开发",
    stage: "预研中",
    visual: "port-keeper",
    downloadHref: "",
    sourceHref: "",
    summary: "把“端口被占用”这件小麻烦，变成一眼可处理的本机面板。",
    manifesto: "开发者每天遇到的小阻塞，也值得被设计成顺手的工具。",
    detail: "它面向本地开发场景：当端口被占用时，不再反复翻终端命令，而是直接看到进程、路径、来源和可执行操作。目标不是替代终端，而是把高频排障压缩成一次确认。",
    privacy: "计划做成本机工具，不需要上传端口或进程数据。",
    features: ["端口占用查看", "进程定位", "快速释放端口", "开发者本机工具"],
    scenes: ["定位冲突端口", "查看进程来源", "安全释放占用"],
    evidence: ["端口 5173", "进程树", "安全释放"],
    prompt: "是谁占用了这个端口，能不能安全处理",
    nextStep: "完成原型后补进程树和安全释放演示",
    releaseNote: "预留为本地开发工具舱，真实截图和源码将在原型稳定后补入。",
    mediaSlots: ["端口列表截图位", "进程树演示位", "安全操作说明位"],
  },
  {
    slug: "ai-voice-input",
    name: "AI 语音输入",
    shortName: "语音输入",
    index: "04",
    status: "planned",
    statusLabel: "计划中",
    openSourceLabel: "免费开源",
    platform: "桌面输入工具",
    stage: "设计中",
    visual: "ai-voice-input",
    downloadHref: "",
    sourceHref: "",
    summary: "一个可接入多家 ASR 的桌面语音输入层，免费、开放、可替换。",
    manifesto: "输入法不该只属于某一个平台，声音也应该有自己的开源入口。",
    detail: "目标是做一个自由、轻量、可替换模型的语音输入工具。它不绑定单一厂商，用户可以接入自己信任的 ASR 服务，也可以把语音输入流程留在自己可控的环境里。",
    privacy: "计划支持用户自配模型与密钥，避免把语音输入锁进单一服务。",
    features: ["多家 ASR 模型接入", "免费开源", "可自部署配置", "桌面级语音输入"],
    scenes: ["快速转写", "切换 ASR 模型", "本地配置密钥与隐私边界"],
    evidence: ["ASR provider", "浮动输入条", "本地密钥"],
    prompt: "把这段语音转成可直接输入的文本",
    nextStep: "补充录音浮窗、模型切换和转写演示",
    releaseNote: "预留为免费开源工具舱，后续会补真实录音、转写和配置演示。",
    mediaSlots: ["录音浮窗位", "模型配置位", "转写演示位"],
  },
];
