export const siteMeta = {
  name: "夜航船之书",
  version: "0.0.1",
  githubHref: "https://github.com/xuelinf/nightsailing",
};

export const products = [
  {
    slug: "ai-sailing-log",
    name: "AI航行日记",
    status: "available",
    statusLabel: "可下载",
    openSourceLabel: "已开源",
    platform: "macOS",
    downloadHref: "/downloads/AI航行日记-0.1.0.dmg",
    sourceHref: "https://github.com/xuelinf/vibe-token-usage",
    summary: "读取本机 Codex 与 Claude Code 使用记录，查看 token 消耗、额度和近期使用节奏。",
    detail: "它把散落在本机日志里的 AI 使用轨迹收束成菜单栏里的日记：今日消耗、额度窗口、小时分布和近期热力图都在一个安静的小面板里。",
    privacy: "默认只读取本机日志，不上传数据。",
    features: ["Codex 与 Claude Code 用量聚合", "今日 token 与额度窗口", "近期使用热力图", "macOS 菜单栏常驻"],
  },
  {
    slug: "wenxuan",
    name: "问玄",
    status: "available",
    statusLabel: "可下载",
    openSourceLabel: "暂未开源",
    platform: "macOS",
    downloadHref: "/downloads/问玄.dmg",
    sourceHref: "",
    summary: "从铜钱起卦、结构化排盘到 AI 解卦，把传统流程收进 macOS 托盘。",
    detail: "问玄把问题、摇卦、六爻排盘和模型解读连成一个完整流程。它保留仪式感，也让卦盘数据以结构化方式交给 AI 参断。",
    privacy: "AI 解卦通过本地代理读取模型密钥，前端不暴露 API key。",
    features: ["铜钱起卦交互", "六爻结构化排盘", "AI 解卦入口", "macOS 托盘应用"],
  },
  {
    slug: "port-keeper",
    name: "端口占用管理器",
    status: "planned",
    statusLabel: "计划中",
    openSourceLabel: "预留舱位",
    platform: "macOS / 本地开发",
    downloadHref: "",
    sourceHref: "",
    summary: "快速查看端口被谁占用，定位进程，并管理本机端口占用。",
    detail: "面向本地开发场景：当端口被占用时，不再反复翻终端命令，而是直接看到进程、路径和可执行操作。",
    privacy: "计划做成本机工具，不需要上传端口或进程数据。",
    features: ["端口占用查看", "进程定位", "快速释放端口", "开发者本机工具"],
  },
  {
    slug: "ai-voice-input",
    name: "AI 语音输入",
    status: "planned",
    statusLabel: "计划中",
    openSourceLabel: "免费开源",
    platform: "桌面输入工具",
    downloadHref: "",
    sourceHref: "",
    summary: "接入多家语音 ASR 模型，提供可替换模型、可自部署的语音输入能力。",
    detail: "目标是做一个自由、轻量、可替换模型的语音输入工具。它不绑定单一厂商，用户可以接入自己信任的 ASR 服务。",
    privacy: "计划支持用户自配模型与密钥，避免把语音输入锁进单一服务。",
    features: ["多家 ASR 模型接入", "免费开源", "可自部署配置", "桌面级语音输入"],
  },
];
